version: 2

project_name: fiatlux

before:
  hooks:
    - go mod tidy

builds:
  - id: fiatlux
    main: ./cmd/fiatlux
    binary: fiatlux
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: fiatlux
    builds: [fiatlux]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

dockers:
  - goos: linux
    goarch: amd64
    ids: [fiatlux]
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/danielriddell21/fiat-lux:{{ .Tag }}"
      - "ghcr.io/danielriddell21/fiat-lux:edge"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source=https://github.com/danielriddell21/fiat-lux"
      
release:
  github:
    owner: danielriddell21
    name: fiat-lux
  name_template: "v{{ .Version }}"

brews:
  - name: fiatlux
    repository:
      owner: danielriddell21
      name: homebrew-tap
      branch: trunk
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: https://github.com/danielriddell21/fiat-lux
    description: "Let there be light."
    license: MIT
    commit_msg_template: "Brew formula update for fiat-lux {{ .Tag }}"
    install: |
      bin.install "fiatlux"
    test: |
      system "#{bin}/fiatlux", "--version"
